### ISSUE TITLE
Add this project to the MailHog libraries page?

### ISSUE THREAD

**Issue by Potherca** [rpkamp/mailhog-client#11]
You might want to add your project to https://github.com/mailhog/MailHog/blob/master/docs/LIBRARIES.md

This will let people know there is a PHP client they can use!

**Comment by rpkamp** [comment]
I will do that, thanks for pointing it out! :smile:

**Comment by rpkamp** [comment]
PR created: https://github.com/mailhog/MailHog/pull/215
