### ISSUE TITLE
Any delete single message function ?

### ISSUE THREAD

**Issue by nervo** [rpkamp/mailhog-client#38]
Hi,

i'd just like to know if you plan to implement a single message deletion function :)

**Comment by rpkamp** [comment]
I hadn't planned on it, no. But feel free to open a PR.

Otherwise I might get to it later.

**Comment by nervo** [comment]
Something like that https://github.com/rpkamp/mailhog-client/pull/39 ?

**Comment by rpkamp** [comment]
Released in [0.5.0](https://github.com/rpkamp/mailhog-client/releases/tag/0.5.0)
