### ISSUE TITLE
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.

### ISSUE THREAD

**Issue by fundo-moretti** [rpkamp/mailhog-client#57]
Package [php-http/message-factory](https://packagist.org/packages/php-http/message-factory) has been archived on May 13, 2023, it is suggested to use [psr/http-factory](https://packagist.org/packages/psr/http-factory) instead.

**Comment by ericgsmith** [comment]
Releated to this - I am seeing the following error when using this extension:

```
No php-http message factories found. Note that the php-http message factories are deprecated in favor of the PSR-17 message factories. To use the legacy Guzzle, Diactoros or Slim Framework factories of php-http, install php-http/message and php-http/message-factory and the chosen message implementation.  
```

I can resolve this by requiring `php-http/message` - I'm not sure if other upstream dependencies changed to remove this at some stage.

Not wanting to hijack this issue as it seems this problem might be resolved by using `psr/http-factory` as well

**Comment by thibaut-algrin** [comment]
I just made a PR to fix this problem

**Comment by isaacrodriguezcubells** [comment]
I can see that the PR: https://github.com/rpkamp/mailhog-client/pull/58 has been merged, but we need a new release to get those changes.

```
  Problem 1
    - rpkamp/mailhog-behat-extension is locked to version 1.1.0 and an update of this package was not requested.
    - rpkamp/mailhog-behat-extension 1.1.0 requires rpkamp/mailhog-client ^1.0 -> found rpkamp/mailhog-client[1.0.0] but it conflicts with your root composer.json require (dev-master#18c3af6fe0d2415b691a106ade77a9a75acf8b21).
```

Would it be possible to create a new release for **mailhog-client** and require the same version in **mailhog-behat-extension**?

Thank you!

**Comment by rpkamp** [comment]
Tagged as 2.0 now. A new version of `mailhog-behat-extention` will be released shortly with support for `mailhog-client` 2.0.
